<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.EventHubs.Processor" Version="5.11.5" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.62.1" />
    <PackageReference Include="Microsoft.Identity.Web" Version="4.14.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.11" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageReference Include="Oracle.EntityFrameworkCore" Version="8.23.60" />
    <PackageReference Include="Azure.Messaging.EventHubs" Version="5.11.5" />
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.18.2" />
    <PackageReference Include="Confluent.Kafka" Version="2.6.1" />
    <PackageReference Include="IBMMQDotnetClient" Version="9.4.2" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.11" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
    <PackageReference Include="GraphQL.Client" Version="6.1.0" />
    <PackageReference Include="GraphQL.Client.Serializer.SystemTextJson" Version="6.1.0" />
    <PackageReference Include="Grpc.Net.Client" Version="2.66.0" />
    <PackageReference Include="Google.Protobuf" Version="3.28.3" />
    <PackageReference Include="Grpc.Tools" Version="2.66.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MailKit" Version="4.8.0" />
    <PackageReference Include="Twilio" Version="7.6.1" />
    <PackageReference Include="FirebaseAdmin" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InfrastructureLayerDeepDive.Weather.Application\InfrastructureLayerDeepDive.Weather.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Generation\Csv\" />
    <Folder Include="Generation\Pdf\" />
    <Folder Include="Monitoring\ApplicationInsight\" />
  </ItemGroup>

</Project>